language: perl
perl:
  - "5.24"
  - "5.26"

sudo: false
before_install:
    - cpanm -n Alien::git FFI::Platypus FFI::CheckLib Sys::Info Path::Tiny Pod::Weaver::Section::Contributors Test::Pod::Coverage
  - dzil authordeps | cpanm -n
  - dzil listdeps | cpanm -n
  - export ALIEN_XGBOOST_CPUCOUNT=4
  - eval $(curl https://travis-perl.github.io/init) --auto
