language: perl
perl:
  - "5.24"
  - "5.26"

sudo: false
before_install:
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

  - eval $(curl https://travis-perl.github.io/init) --auto
