language: perl
perl:
  - "5.24"
  - "5.26"

sudo: false
before_install:
  - cpanm -n Alien::git
  - dzil authordeps | cpanm -n
  - dzil listdeps | cpanm -n

  - eval $(curl https://travis-perl.github.io/init) --auto
